<?php
/**
 * Author: oswin
 * Time: 2022/8/2-18:19
 * Description:
 * Version: v1.0
 */

namespace Test;

use Web3\Net;

class NetTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->net = new Net($this->testRinkebyHost);
    }

    public function testVersion(): void
    {
        $res = $this->web3->net->version();
        var_dump($res);
        $res = $this->web3->net->net_version();
        var_dump($res);
        $res = $this->web3->getNet()->version();
        var_dump($res);
        $res = $this->web3->getNet()->net_version();
        var_dump($res);
        $res = $this->net->version();
        var_dump($res);
        $res = $this->net->net_version();
        var_dump($res);
        $this->assertTrue(true);
    }

    public function testPeerCount(): void
    {
        $res = $this->web3->net->peerCount();
        var_dump($res);
//        $res = $this->web3->net->net_peerCount();
//        var_dump($res);
//        $res = $this->web3->getNet()->peerCount();
//        var_dump($res);
//        $res = $this->web3->getNet()->net_peerCount();
//        var_dump($res);
//        $res = $this->net->peerCount();
//        var_dump($res);
//        $res = $this->net->net_peerCount();
//        var_dump($res);
        $this->assertTrue(true);
    }
}
